{
  "formatVersion": "1.1",
  "component": {
    "group": "com.apima.lumaris",
    "module": "lumaris",
    "version": "0.3.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.11.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "lumaris-0.3.2.aar",
          "url": "lumaris-0.3.2.aar",
          "size": 6240659,
          "sha512": "eb52eb5cd0d82d4ae0e9c5df9f40a54c43491fd5c2630d300913a5079488da1081ccfedb81ab3a948b58723fedf48905ac37d20403cdaf17dbaafd165558f822",
          "sha256": "a34cef170c40c17b75e864e6e12bcbed6a15f96ac9114ca4545562c568ba65b0",
          "sha1": "e97ea3b4ce8f8654eb229147eb75437400e4d1c8",
          "md5": "a46d8edc765d6a090f730d48f6870656"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.google.mediapipe",
          "module": "tasks-vision",
          "version": {
            "requires": "0.10.29"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.11.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "lumaris-0.3.2.aar",
          "url": "lumaris-0.3.2.aar",
          "size": 6240659,
          "sha512": "eb52eb5cd0d82d4ae0e9c5df9f40a54c43491fd5c2630d300913a5079488da1081ccfedb81ab3a948b58723fedf48905ac37d20403cdaf17dbaafd165558f822",
          "sha256": "a34cef170c40c17b75e864e6e12bcbed6a15f96ac9114ca4545562c568ba65b0",
          "sha1": "e97ea3b4ce8f8654eb229147eb75437400e4d1c8",
          "md5": "a46d8edc765d6a090f730d48f6870656"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lumaris-0.3.2-javadoc.jar",
          "url": "lumaris-0.3.2-javadoc.jar",
          "size": 709581,
          "sha512": "80023e874c8d95a205abea4cfc31b50f447e0bacde4fa1191234947e088c563ff2dccde2825f6a6109f6aa2368496bea8b64d290a8ad556570cefe26c387282c",
          "sha256": "b854ca34d4e5d22865206e3d2926542b9c4b50899cf7bb793bbbb04bbaedf117",
          "sha1": "3255d56499976b531f167de0eb92d3a9a9a08a96",
          "md5": "7941335920bee017ab1492637c86b041"
        }
      ]
    }
  ]
}
